add file modal.html  in index.html, add modal.js in index.js, add in …
lumpy-the-moose/team-11-project pull request #15
Opened 2022-10-30 22:59 UTC by VladimirKovalenko1986

Додав файл modal.html, додав в modal.js  noscroll для body, додав modal.scss, в mixines додав свої міксіни подивися, додав в common.scss загальні стилі для button, додав для colors.scss border color для інпута.

2022-10-30 23:14 UTC, lumpy-the-moose requested changes

2022-10-30 23:14 UTC, lumpy-the-moose commented on src/js/modal.js
> -    openModalBtnList: document.querySelectorAll('[data-modal-open]'),
не змінюйте modal.js, він повинен вибирати всі кнопки відкриття на сторінці

2022-10-30 23:14 UTC, lumpy-the-moose commented on src/sass/utils/_colors.scss
> +$color-border-pasiv-input-modal: rgba(18, 18, 18, 0.12);
вже є такий колір $color-input-border: #1212121f;

2022-10-30 23:14 UTC, lumpy-the-moose commented on src/sass/utils/_common.scss
> +button {
чому би не обʼєднати button та .btn в placeholder 
%button {
  border: 0;
  padding: 0;
  cursor: pointer;
  @include font(13px, 500, 1.5);
  border-radius: 30px;
  color: $color-text;
}

2022-10-31 11:33 UTC, VladimirKovalenko1986 commented on src/js/modal.js
> -    openModalBtnList: document.querySelectorAll('[data-modal-open]'),
Ок залишив як є

2022-10-31 11:34 UTC, VladimirKovalenko1986 commented on src/sass/utils/_colors.scss
> +$color-border-pasiv-input-modal: rgba(18, 18, 18, 0.12);
Видалив

2022-10-31 11:34 UTC, VladimirKovalenko1986 commented on src/sass/utils/_common.scss
> +button {
Створений

2022-10-31 17:19 UTC, lumpy-the-moose requested changes

2022-10-31 17:19 UTC, lumpy-the-moose commented on src/sass/index.css.map
> +{"version":3,"sources":["utils/_common.scss","utils/_colors.scss","index.css","utils/_pleasholder.scss","utils/_mixins.scss","components/_hero.scss","components/_modal.scss"],"names":[],"mappings":"A
звідки цей css.map взявся? watch sass потрібно виключити

2022-10-31 17:19 UTC, lumpy-the-moose commented on src/sass/utils/_common.scss
> +  min-width: 320px;
тут ок

2022-10-31 17:19 UTC, lumpy-the-moose commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
watch sass відключити

2022-10-31 17:19 UTC, lumpy-the-moose commented on src/sass/utils/_placeholders.scss
> +%btn {
placeholders - граматична помилка, я виправив

2022-11-01 06:19 UTC, lumpy-the-moose approved these changes

2022-11-01 07:03 UTC, merged