Created footer
lumpy-the-moose/team-11-project pull request #19
Opened 2022-10-31 13:25 UTC by AnastasiaMosevych

### Reviewers

- [ ] @lumpy-the-moose 

---

### Summary of issue

Wrote layout for footer partial in footer.html, applied styles for mobile, tablet and desktop viewport, added images for footer background image.

---

### Summary of change

Зроблено: 
* верстка і стилі для футера в мобільній версії, версіях для планшета і десктопа.
* вирівняла лого по відношенню до site-nav в планшетній і десктопній версіях.
* пофіксила афтери в полісах, щоб вони займали 100% ширини тексту.

<img width="376" alt="Screenshot 2022-10-31 at 16 19 18" src="https://user-images.githubusercontent.com/111194179/199043922-615900f6-22ba-43cc-bcaa-64231ca9b1d2.png">
<img width="578" alt="Screenshot 2022-10-31 at 16 12 46" src="https://user-images.githubusercontent.com/111194179/199042754-10caf9fa-e668-43d0-8169-6c0f4a081ef8.png">
<img width="873" alt="Screenshot 2022-10-31 at 16 13 11" src="https://user-images.githubusercontent.com/111194179/199042758-9db3868d-86e8-4396-bf07-4157a68858f7.png">

---

### To-Do

Мені ще треба доробити:

- в мобільній версії 
-- щоб бекграунд-картинка не лізла вгору, коли розширюється екран
- в десктопі
--щоб не обрізалася бекграунд-картинка

2022-10-31 19:24 UTC, lumpy-the-moose requested changes

2022-10-31 19:24 UTC, lumpy-the-moose commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
index.css? sass compiler потрібно вимкнути, принаймі на час проекту

2022-10-31 19:24 UTC, lumpy-the-moose commented on src/sass/index.css.map
> +{"version":3,"sources":["utils/_common.scss","utils/_colors.scss","index.css","components/_hero.scss","components/_footer.scss"],"names":[],"mappings":"AAAQ,6DAAA;AACA,4FAAA;AAER;EACE,yBCJiB;EDKjB,cC
аналогічно)

2022-10-31 21:41 UTC, AnastasiaMosevych commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
Done :)

2022-10-31 21:41 UTC, AnastasiaMosevych commented on src/sass/index.css
> +@import '~node_modules/modern-normalize/modern-normalize.css';
Done :)

2022-10-31 21:41 UTC, AnastasiaMosevych commented on src/sass/index.css.map
> +{"version":3,"sources":["utils/_common.scss","utils/_colors.scss","index.css","components/_hero.scss","components/_footer.scss"],"names":[],"mappings":"AAAQ,6DAAA;AACA,4FAAA;AAER;EACE,yBCJiB;EDKjB,cC
Done :)

2022-11-01 04:56 UTC, lumpy-the-moose approved these changes
ок, приймаю

2022-11-01 04:56 UTC, merged