Features/subscribe2
lumpy-the-moose/team-11-project pull request #43
Opened 2022-11-03 15:47 UTC by EmirovAtem

2022-11-03 18:52 UTC, Khavkin requested changes
Спробуй будь ласка сам банан по висоті позиціонувати не виходячі за рамки секції. А піднімати до гори усю секцію за допомогою від'ємного марджина.

2022-11-03 18:52 UTC, Khavkin commented on src/sass/components/_subscribe.scss
>        display: flex;
Додай ще align-items: center;

2022-11-03 18:52 UTC, Khavkin commented on src/sass/components/_subscribe.scss
> +    top: -95px;
Зроби центрування банану в розмірах до 767px, бо він тусується десь зліва.

2022-11-04 09:09 UTC, lumpy-the-moose approved these changes
Поправив банан в мобілці, там була якась біда)

2022-11-04 09:18 UTC, merged